index:
  path: /
  parameters: {}
  controller: \Src\Controller\VisitorController
  action: goToIndex

menu:
  path: /play
  parameters: {}
  controller: \Src\Controller\VisitorController
  action: goToMenu

nbSelect:
  path: /play/sel-col-nb/:filt
  parameters: {filt: '?<filt>[A-Za-z]+'}
  controller: \Src\Controller\VisitorController
  action: nbColSelect

model:
  path: /play/model
  parameters: {}
  controller: \Src\Controller\VisitorController
  action: goToModel

gameOneByMenu:
  path: /play/game-one
  parameters: {}
  controller: \Src\Controller\VisitorController
  action: goFromMenuToGameOne

gameOneByModel:
  path: /play/model/game-one
  parameters: {}
  controller: \Src\Controller\VisitorController
  action: goFromModelToGameOne

gameTwo:
  path: /play/game-two
  parameters: {}
  controller: \Src\Controller\VisitorController
  action: goToGameTwo

result:
  path: /play/result
  parameters: {}
  controller: \Src\Controller\VisitorController
  action: goToResult

connexion:
  path: /connexion
  parameters: {}
  controller: \Src\Controller\VisitorController
  action: checkConnectInfo

admin:
  path: /admin
  parameters: {}
  controller: \Src\Controller\AdminController
  action: goToAdmin

addForm:
  path: /admin/form/add
  parameters: {}
  controller: \Src\Controller\AdminController
  action: getAddColBlock

updateForm:
  path: /admin/form/update
  parameters: {}
  controller: \Src\Controller\AdminController
  action: getUpdColBlock

colorTable:
  path: /admin/table/:colGrp
  parameters: {colGrp: '?<colGrp>[a-zA-Z]+'}
  controller: \Src\Controller\AdminController
  action: getColTableBlock

add:
  path: /admin/add
  parameters: {}
  controller: \Src\Controller\AdminController
  action: addAction

delete:
  path: /admin/delete/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\AdminController
  action: deleteAction

update:
  path: /admin/update/:colGrp/:id
  parameters: {colGrp: '?<colGrp>[a-zA-Z]+', id: '?<id>[\d]+'}
  controller: \Src\Controller\AdminController
  action: updateAction
